CREATE DATABASE customer;
CREATE DATABASE notification;
CREATE DATABASE fraud;

GRANT ALL PRIVILEGES ON DATABASE customer TO usuario;
GRANT ALL PRIVILEGES ON DATABASE notification TO usuario;
GRANT ALL PRIVILEGES ON DATABASE fraud TO usuario;