server:
  port: 8081
spring:
  application:
    name: costumer
  datasource:
    username: usuario
    password: senha
    url: jdbc:postgresql://localhost:5432/costumer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    costumer: costumer.queue
  routing-keys:
    internal-costumer: internal.costumer.routing-key

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: localhost:9411/api/v2/spans