### Get All Users
GET http://{{host}}/customers
Accept: application/json
#Authorization: {{BearerToken}}

# Redirect to
#>> data-customer.json

### Create New customer
#< {%
#    pre-request config
#    request.variables.set("key", "value");
#    POST path/param?{{key}}
#%}
POST http://{{host}}/customers
Accept: application/json
Content-Type: application/json

{
  "firstname": "{{$random.alphabetic(8)}}",
  "lastname": "{{$random.alphabetic(8)}}",
  "email": "{{$random.email}}"
}

> {%
    client.test('POST new customer returns 200', function () {
        client.assert(response.status === 200);
        // TODO: Testing
    });
%}