### Create New Notification
POST http://{{host}}/notification
Accept: application/json
Content-Type: application/json

{
  "toCostumerId": "1",
  "toCostumerEmail": "{{$random.email}}",
  "message": "{{$random.alphabetic(20)}}"
}

> {%
    client.test('POST new notification returns 201', function () {
        client.assert(response.status === 201);
        // TODO: Testing
    });
%}

### Get All Notifications
GET http://${{host}}/notification
Accept: application/json
#Authorization: {{BearerToken}}

# Redirect to
#>> data-costumer.json