### Create New Notification
POST http://{{host}}/notification
Accept: application/json
Content-Type: application/json

{
  "toCustomerId": 1,
  "toCustomerEmail": "{{$random.email}}",
  "message": "{{$random.alphabetic(20)}}"
}

> {%
    client.test('POST new notification returns 200', function () {
        client.assert(response.status === 200);
        // TODO: Testing
    });
%}

### Get All Notifications
GET http://{{host}}/notification
Accept: application/json
#Authorization: {{BearerToken}}

# Redirect to
#>> data-customer.json