spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  tracing:
    enabled: false
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans